FORMAT: 1A
HOST: https://gamelookup.me/api

# GameLookup

GameLookup is your one-stop-shop for all you curious gamer needs.


## GameLookup Database [/search?{query}&{limit}]

### Search our Database [GET]

+ Parameters
    + query - query string
    + limit - number of returned items limit
    
+ Response 200 (application/json)

        {
         "Results": [
                {
                    "type": "Game",
                    "title": "Test game",
                    "route": "/games/1234",
                    "image": "image source"
                },
                {
                    "type": "Publisher",
                    "title": "Test Company",
                    "route": "/publishers/1234",
                    "image": "image source"  
                },
                {
                    "type": "Genre",
                    "title": "Test Genre",
                    "route": "/genre/1234",
                    "image": "image source"  
                }
            ]
        }


## Game Collection [/games/]

### List Game Collection [GET]

+ Response 200 (application/json)

        {
         "Games": [
                {
                    "id": 1234,
                    "title": "Test game",
                    "number of players": "2",
                    "theme": "Action",
                    "year published": "2000",
                    "avgerage player score": "1234",
                    "systems": "systems"
                },
                {
                    "id": 1235,
                    "title": "Tester game",
                    "number of players": "1",
                    "theme": "Adventure",
                    "year published": "2000",
                    "avgerage player score": "1234",
                    "systems": "systems"
                }
            ]
        }


## Game Information [/games/{id}]

### Get Game Info [GET]

+ Parameters
    + id (number) - ID of game

+ Response 200 (application/json)

        {
         "Game": [
                {
                    "id": 1235,
                    "title": "Tester game",
                    "number of players": "1",
                    "theme": "Adventure",
                    "year published": "2000",
                    "avgerage player score": "1234",
                    "systems": "systems"
                }
            ]
        }


## Publisher Collection [/publishers/]

### List Publisher Collection [GET]

+ Response 200 (application/json)

        {
         "Publishers": [
                {
                    "id": 642,
                    "name": "testcompany1",
                    "number of games": "123",
                    "year founded": "2000",
                    "country founded": "country A",
                    "number of franchises": 12,
                    "average number of DLCs": 12
                },
                {
                    "id": 212,
                    "name": "testcompany2",
                    "number of games": "234",
                    "year founded": "2014",
                    "country founded": "country B",
                    "number of franchises": 12,
                    "average number of DLCs": 12
                }
            ]
        }



## Publisher Information [/publishers/{id}]

### Get Publisher Info [GET]

+ Parameters
    + id (number) - ID of company/publisher

+ Response 200 (application/json)

        {
         "Publisher": [
                {
                    "id": 642,
                    "name": "testcompany1",
                    "number of games": "123",
                    "year founded": "2000",
                    "country founded": "country A",
                    "number of franchises": 12,
                    "average number of DLCs": 12
                }
            ]
        }


## Genre Collection [/genres/]

### List Genre Collection [GET]

+ Response 200 (application/json)

        {
         "Genres": [
                {
                    "id": 1,
                    "name": "Action",
                    "number of games": 12345,
                    "average rating": "rating"
                    "popularity": "popular",
                    "related genres": ["genre1", "genre2", "genre3"]
                },
                {
                    "id": 2,
                    "name": "Adventure",
                    "number of games": 12345,
                    "average rating": "rating"
                    "popularity": "popular",
                    "related genres": ["genre1", "genre2"]
                }
            ]
        }


## Genre Information [/genres/{id}]

### Get Genre Info [GET]

+ Parameters
    + id (number) - ID of genre/theme

+ Response 200 (application/json)

        {
         "Genre": [
                {
                    "id": 1,
                    "name": "Action",
                    "number of games": 12345,
                    "average rating": "rating"
                    "popularity": "popular",
                    "related genres": ["genre1", "genre2", "genre3"]
                }
            ]
        }