FORMAT: 1A
HOST: https://gamelookup.me/api

# GameLookup

GameLookup is your one-stop-shop for all you curious gamer needs.


## GameLookup Database [/search?{query}&{limit}]

### Search our Database [GET]

+ Parameters
    + query - query string
    + limit - number of returned items limit
    
+ Response 200 (application/json)

        {
         "Results": [
                {
                    "type": "Game",
                    "title": "Test game",
                    "route": "/games/1234",
                    "image": "image source"
                },
                {
                    "type": "Publisher",
                    "title": "Test Company",
                    "route": "/publishers/1234",
                    "image": "image source"  
                },
                {
                    "type": "Character",
                    "name": "PersonA",
                    "route": "/characters/1234",
                    "image": "image source"  
                }
            ]
        }


## Game Collection [/games/]

### List Game Collection [GET]

+ Response 200 (application/json)

        {
         "Games": [
                {
                    "id": 1234,
                    "title": "Test game",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2000",
                    "average player score": "1234"
                },
                {
                    "id": 1235,
                    "title": "Tester game",
                    "publisher": "Company 2",
                    "theme": "Adventure",
                    "year published": "2000",
                    "average player score": "1234"
                }
            ]
        }


## Game Information [/games/{id}]

### Get Game Info [GET]

+ Parameters
    + id (number) - ID of game

+ Response 200 (application/json)

        {
         "Game": [
                {
                    "id": 1234,
                    "title": "Test game",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2000",
                    "average player score": "1234"
                }
            ]
        }


## Game with Character Information [/games/{id}//characters]

### List Game with Character Info [GET]

+ Parameters
    + id (number) - ID of game

+ Response 200 (application/json)

        {
         "Character": [
                {
                    "id": 1,
                    "name": "Name 1",
                    "gender": "female",
                    "franchise": "Franchise A"
                    "location": "In Game Location",
                    "first game": "Game A"
                }
            ],
         "Game":[
                {
                    "id": 1234,
                    "title": "Test game",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2000",
                    "average player score": "1234"
                }
            ]
        }
     
        
## Game with Publisher Information [/games/{id}//publishers]

### List Game with Publisher Info [GET]

+ Parameters
    + id (number) - ID of game

+ Response 200 (application/json)

        {
         "Publisher": [
                {
                    "id": 642,
                    "title": "testcompany1",
                    "year founded": "2000",
                    "country": "country A",
                    "website": "testweb.com",
                    "number of games": 12
                }
            ],
         "Game":[
                {
                    "id": 1234,
                    "title": "Test game",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2000",
                    "average player score": "1234"
                }
            ]
        }


## Publisher Collection [/publishers/]

### List Publisher Collection [GET]

+ Response 200 (application/json)

        {
         "Publishers": [
                {
                    "id": 642,
                    "title": "testcompany1",
                    "year founded": "2000",
                    "country": "country A",
                    "website": "testweb.com",
                    "number of games": 12
                },
                {
                    "id": 212,
                    "name": "testcompany2",
                    "year founded": "2014",
                    "country": "country B",
                    "website": "testweb2.com",
                    "number of games": 234
                }
            ]
        }



## Publisher Information [/publishers/{id}]

### Get Publisher Info [GET]

+ Parameters
    + id (number) - ID of company/publisher

+ Response 200 (application/json)

        {
         "Publisher": [
                {
                    "id": 642,
                    "title": "testcompany1",
                    "year founded": "2000",
                    "country": "country A",
                    "website": "testweb.com",
                    "number of games": 12
                }
            ]
        }


## Publisher with Games Information [/publishers/{id}//games]

### List Publisher with Games Info [GET]

+ Parameters
    + id (number) - ID of publisher

+ Response 200 (application/json)

        {
         "Games": [
                {
                    "id": 1234,
                    "title": "Test game",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2000",
                    "average player score": "1234"
                },
                {
                    "id": 1345,
                    "title": "Test game2",
                    "publisher": "Company 1",
                    "theme": "Action",
                    "year published": "2004",
                    "average player score": "1432"
                }
            ],
         "Publisher":[
                {
                    "id": 642,
                    "title": "testcompany1",
                    "year founded": "2000",
                    "country": "country A",
                    "website": "testweb.com",
                    "number of games": 12
                }
            ]
        }

## Character Collection [/characters/]

### List Character Collection [GET]

+ Response 200 (application/json)

        {
         "Character": [
                {
                    "id": 1,
                    "name": "Name 1",
                    "gender": "female",
                    "franchise": "Franchise yA"
                    "location": "In Game Location",
                    "first game": "Game A"
                },
                {
                    "id": 2,
                    "name": "Name 2",
                    "gender": "male",
                    "franchise": "Franchise B"
                    "location": "In Game Location",
                    "first game": "Game B"
                }
            ]
        }


## Character Information [/characters/{id}]

### Get Character Info [GET]

+ Parameters
    + id (number) - ID of character

+ Response 200 (application/json)

        {
         "Character": [
                {
                    "id": 1,
                    "name": "Name 1",
                    "gender": "female",
                    "franchise": "Franchise A"
                    "location": "In Game Location",
                    "first game": "Game A"
                }
            ]
        }